package cz.mg.vulkantransformator.gui;


public class ComparisionWindow extends javax.swing.JFrame {
    public ComparisionWindow(String structure, String vk, String vulkan) {
        initComponents();
        jTextAreaStructure.setText(structure);
        jTextAreaVk.setText(vk);
        jTextAreaVulkan.setText(vulkan);
        setSize(1366, 768);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanelVk = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaVk = new javax.swing.JTextArea();
        jPanelVulkan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaVulkan = new javax.swing.JTextArea();
        jPanelC = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaStructure = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comparision");
        getContentPane().setLayout(new java.awt.GridLayout());

        jSplitPane1.setDividerLocation(455);
        jSplitPane1.setResizeWeight(0.3);

        jSplitPane2.setDividerLocation(455);
        jSplitPane2.setResizeWeight(0.5);

        jPanelVk.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelVk.setPreferredSize(new java.awt.Dimension(0, 0));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWeights = new double[] {1.0};
        jPanel2Layout.rowWeights = new double[] {0.0, 1.0};
        jPanelVk.setLayout(jPanel2Layout);

        jLabel2.setText("Vk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 2, 4);
        jPanelVk.add(jLabel2, gridBagConstraints);

        jTextAreaVk.setColumns(20);
        jTextAreaVk.setRows(5);
        jScrollPane2.setViewportView(jTextAreaVk);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 4, 4);
        jPanelVk.add(jScrollPane2, gridBagConstraints);

        jSplitPane2.setLeftComponent(jPanelVk);

        jPanelVulkan.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelVulkan.setPreferredSize(new java.awt.Dimension(0, 0));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWeights = new double[] {1.0};
        jPanel3Layout.rowWeights = new double[] {0.0, 1.0};
        jPanelVulkan.setLayout(jPanel3Layout);

        jLabel3.setText("Vulkan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 2, 4);
        jPanelVulkan.add(jLabel3, gridBagConstraints);

        jTextAreaVulkan.setColumns(20);
        jTextAreaVulkan.setRows(5);
        jScrollPane3.setViewportView(jTextAreaVulkan);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 4, 4);
        jPanelVulkan.add(jScrollPane3, gridBagConstraints);

        jSplitPane2.setRightComponent(jPanelVulkan);

        jSplitPane1.setRightComponent(jSplitPane2);

        jPanelC.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelC.setPreferredSize(new java.awt.Dimension(0, 0));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWeights = new double[] {1.0};
        jPanel1Layout.rowWeights = new double[] {0.0, 1.0};
        jPanelC.setLayout(jPanel1Layout);

        jLabel1.setText("Car");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 2, 4);
        jPanelC.add(jLabel1, gridBagConstraints);

        jTextAreaStructure.setColumns(20);
        jTextAreaStructure.setRows(5);
        jScrollPane1.setViewportView(jTextAreaStructure);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 4, 4);
        jPanelC.add(jScrollPane1, gridBagConstraints);

        jSplitPane1.setLeftComponent(jPanelC);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelC;
    private javax.swing.JPanel jPanelVk;
    private javax.swing.JPanel jPanelVulkan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextArea jTextAreaStructure;
    private javax.swing.JTextArea jTextAreaVk;
    private javax.swing.JTextArea jTextAreaVulkan;
    // End of variables declaration//GEN-END:variables
}
