package cz.mg.vulkantransformator.gui;


public class MainWindow extends javax.swing.JFrame {
    private final MainWindowState state;

    public MainWindow() {
        initComponents();
        state = new MainWindowState(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelPaths = new javax.swing.JPanel();
        jLabelVulkanCore = new javax.swing.JLabel();
        jTextFieldVulkanCorePath = new javax.swing.JTextField();
        jButtonVulkanCore = new javax.swing.JButton();
        jLabelOutputDirectory = new javax.swing.JLabel();
        jTextFieldOutputDirectory = new javax.swing.JTextField();
        jButtonOutputDirectory = new javax.swing.JButton();
        jScrollPaneGenerators = new javax.swing.JScrollPane();
        jPanelGenerators = new javax.swing.JPanel();
        jCheckBoxSystemTypes = new javax.swing.JCheckBox();
        jCheckBoxTypes = new javax.swing.JCheckBox();
        jCheckBoxEnums = new javax.swing.JCheckBox();
        jCheckBoxFlags = new javax.swing.JCheckBox();
        jCheckBoxFlagBits = new javax.swing.JCheckBox();
        jCheckBoxHandles = new javax.swing.JCheckBox();
        jCheckBoxStructures = new javax.swing.JCheckBox();
        jCheckBoxUnions = new javax.swing.JCheckBox();
        jCheckBoxInfos = new javax.swing.JCheckBox();
        jCheckBoxArrays = new javax.swing.JCheckBox();
        jCheckBoxCallbacks = new javax.swing.JCheckBox();
        jCheckBoxFunctions = new javax.swing.JCheckBox();
        jCheckBoxExtensions = new javax.swing.JCheckBox();
        jCheckBoxDefines = new javax.swing.JCheckBox();
        jCheckBoxMisc = new javax.swing.JCheckBox();
        jButtonSystemTypes = new javax.swing.JButton();
        jButtonTypes = new javax.swing.JButton();
        jButtonEnums = new javax.swing.JButton();
        jButtonFlags = new javax.swing.JButton();
        jButtonFlagBits = new javax.swing.JButton();
        jButtonHandles = new javax.swing.JButton();
        jButtonStructures = new javax.swing.JButton();
        jButtonUnions = new javax.swing.JButton();
        jButtonInfos = new javax.swing.JButton();
        jButtonArrays = new javax.swing.JButton();
        jButtonCallbacks = new javax.swing.JButton();
        jButtonFunctions = new javax.swing.JButton();
        jButtonExtensions = new javax.swing.JButton();
        jButtonDefines = new javax.swing.JButton();
        jButtonMisc = new javax.swing.JButton();
        jTextFieldSystemTypes = new javax.swing.JTextField();
        jTextFieldTypes = new javax.swing.JTextField();
        jTextFieldEnums = new javax.swing.JTextField();
        jTextFieldFlags = new javax.swing.JTextField();
        jTextFieldFlagBits = new javax.swing.JTextField();
        jTextFieldHandles = new javax.swing.JTextField();
        jTextFieldStructures = new javax.swing.JTextField();
        jTextFieldUnions = new javax.swing.JTextField();
        jTextFieldInfos = new javax.swing.JTextField();
        jTextFieldArrays = new javax.swing.JTextField();
        jTextFieldCallbacks = new javax.swing.JTextField();
        jTextFieldFunctions = new javax.swing.JTextField();
        jTextFieldExtensions = new javax.swing.JTextField();
        jTextFieldDefines = new javax.swing.JTextField();
        jTextFieldMisc = new javax.swing.JTextField();
        jPanelHorizontalSpacer = new javax.swing.JPanel();
        jPanelVertical = new javax.swing.JPanel();
        jPanelFooter = new javax.swing.JPanel();
        jButtonSelectAll = new javax.swing.JButton();
        jButtonUnselectAll = new javax.swing.JButton();
        jPanelDummy = new javax.swing.JPanel();
        jLabelStatus = new javax.swing.JLabel();
        jButtonGenerateSelected = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VulkanTranformator");
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWeights = new double[] {1.0};
        layout.rowWeights = new double[] {0.0, 1.0, 0.0};
        getContentPane().setLayout(layout);

        jPanelPaths.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWeights = new double[] {0.0, 1.0, 0.0};
        jPanel1Layout.rowWeights = new double[] {1.0};
        jPanelPaths.setLayout(jPanel1Layout);

        jLabelVulkanCore.setText("Vulkan core");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 2, 4);
        jPanelPaths.add(jLabelVulkanCore, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 2, 4);
        jPanelPaths.add(jTextFieldVulkanCorePath, gridBagConstraints);

        jButtonVulkanCore.setText("...");
        jButtonVulkanCore.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVulkanCoreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 2, 4);
        jPanelPaths.add(jButtonVulkanCore, gridBagConstraints);

        jLabelOutputDirectory.setText("Output directory");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanelPaths.add(jLabelOutputDirectory, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanelPaths.add(jTextFieldOutputDirectory, gridBagConstraints);

        jButtonOutputDirectory.setText("...");
        jButtonOutputDirectory.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOutputDirectoryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 4);
        jPanelPaths.add(jButtonOutputDirectory, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 2, 4);
        getContentPane().add(jPanelPaths, gridBagConstraints);

        jPanelGenerators.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        java.awt.GridBagLayout jPanelGeneratorsLayout = new java.awt.GridBagLayout();
        jPanelGeneratorsLayout.columnWeights = new double[] {0.0, 0.0, 0.0, 0.0, 1.0};
        jPanelGeneratorsLayout.rowWeights = new double[] {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0};
        jPanelGenerators.setLayout(jPanelGeneratorsLayout);

        jCheckBoxSystemTypes.setSelected(true);
        jCheckBoxSystemTypes.setText("System types");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 2, 2);
        jPanelGenerators.add(jCheckBoxSystemTypes, gridBagConstraints);

        jCheckBoxTypes.setSelected(true);
        jCheckBoxTypes.setText("Types");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 2);
        jPanelGenerators.add(jCheckBoxTypes, gridBagConstraints);

        jCheckBoxEnums.setSelected(true);
        jCheckBoxEnums.setText("Enums");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 2);
        jPanelGenerators.add(jCheckBoxEnums, gridBagConstraints);

        jCheckBoxFlags.setSelected(true);
        jCheckBoxFlags.setText("Flags");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 2);
        jPanelGenerators.add(jCheckBoxFlags, gridBagConstraints);

        jCheckBoxFlagBits.setSelected(true);
        jCheckBoxFlagBits.setText("Flag bits");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 2);
        jPanelGenerators.add(jCheckBoxFlagBits, gridBagConstraints);

        jCheckBoxHandles.setSelected(true);
        jCheckBoxHandles.setText("Handles");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 2);
        jPanelGenerators.add(jCheckBoxHandles, gridBagConstraints);

        jCheckBoxStructures.setSelected(true);
        jCheckBoxStructures.setText("Structures");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 2);
        jPanelGenerators.add(jCheckBoxStructures, gridBagConstraints);

        jCheckBoxUnions.setSelected(true);
        jCheckBoxUnions.setText("Unions");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 2);
        jPanelGenerators.add(jCheckBoxUnions, gridBagConstraints);

        jCheckBoxInfos.setSelected(true);
        jCheckBoxInfos.setText("Infos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 2);
        jPanelGenerators.add(jCheckBoxInfos, gridBagConstraints);

        jCheckBoxArrays.setSelected(true);
        jCheckBoxArrays.setText("Arrays");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 2);
        jPanelGenerators.add(jCheckBoxArrays, gridBagConstraints);

        jCheckBoxCallbacks.setSelected(true);
        jCheckBoxCallbacks.setText("Callbacks");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 2);
        jPanelGenerators.add(jCheckBoxCallbacks, gridBagConstraints);

        jCheckBoxFunctions.setSelected(true);
        jCheckBoxFunctions.setText("Functions");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 2);
        jPanelGenerators.add(jCheckBoxFunctions, gridBagConstraints);

        jCheckBoxExtensions.setSelected(true);
        jCheckBoxExtensions.setText("Extensions");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 2);
        jPanelGenerators.add(jCheckBoxExtensions, gridBagConstraints);

        jCheckBoxDefines.setSelected(true);
        jCheckBoxDefines.setText("Defines");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 2);
        jPanelGenerators.add(jCheckBoxDefines, gridBagConstraints);

        jCheckBoxMisc.setSelected(true);
        jCheckBoxMisc.setText("Misc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 4, 2);
        jPanelGenerators.add(jCheckBoxMisc, gridBagConstraints);

        jButtonSystemTypes.setText("Test");
        jButtonSystemTypes.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemTypesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 2, 2);
        jPanelGenerators.add(jButtonSystemTypes, gridBagConstraints);

        jButtonTypes.setText("Test");
        jButtonTypes.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTypesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelGenerators.add(jButtonTypes, gridBagConstraints);

        jButtonEnums.setText("Test");
        jButtonEnums.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnumsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelGenerators.add(jButtonEnums, gridBagConstraints);

        jButtonFlags.setText("Test");
        jButtonFlags.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlagsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelGenerators.add(jButtonFlags, gridBagConstraints);

        jButtonFlagBits.setText("Test");
        jButtonFlagBits.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlagBitsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelGenerators.add(jButtonFlagBits, gridBagConstraints);

        jButtonHandles.setText("Test");
        jButtonHandles.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHandlesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelGenerators.add(jButtonHandles, gridBagConstraints);

        jButtonStructures.setText("Test");
        jButtonStructures.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStructuresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelGenerators.add(jButtonStructures, gridBagConstraints);

        jButtonUnions.setText("Test");
        jButtonUnions.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnionsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelGenerators.add(jButtonUnions, gridBagConstraints);

        jButtonInfos.setText("Test");
        jButtonInfos.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelGenerators.add(jButtonInfos, gridBagConstraints);

        jButtonArrays.setText("Test");
        jButtonArrays.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArraysActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelGenerators.add(jButtonArrays, gridBagConstraints);

        jButtonCallbacks.setText("Test");
        jButtonCallbacks.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCallbacksActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelGenerators.add(jButtonCallbacks, gridBagConstraints);

        jButtonFunctions.setText("Test");
        jButtonFunctions.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFunctionsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelGenerators.add(jButtonFunctions, gridBagConstraints);

        jButtonExtensions.setText("Test");
        jButtonExtensions.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtensionsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelGenerators.add(jButtonExtensions, gridBagConstraints);

        jButtonDefines.setText("Test");
        jButtonDefines.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDefinesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelGenerators.add(jButtonDefines, gridBagConstraints);

        jButtonMisc.setText("Test");
        jButtonMisc.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMiscActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 4, 2);
        jPanelGenerators.add(jButtonMisc, gridBagConstraints);

        jTextFieldSystemTypes.setText("uint32_t");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 2, 4);
        jPanelGenerators.add(jTextFieldSystemTypes, gridBagConstraints);

        jTextFieldTypes.setText("VkBool32");
        jTextFieldTypes.setMinimumSize(new java.awt.Dimension(320, 19));
        jTextFieldTypes.setPreferredSize(new java.awt.Dimension(320, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 4);
        jPanelGenerators.add(jTextFieldTypes, gridBagConstraints);

        jTextFieldEnums.setText("VkDynamicState");
        jTextFieldEnums.setMinimumSize(new java.awt.Dimension(320, 19));
        jTextFieldEnums.setPreferredSize(new java.awt.Dimension(320, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 4);
        jPanelGenerators.add(jTextFieldEnums, gridBagConstraints);

        jTextFieldFlags.setText("VkImageAspectFlags");
        jTextFieldFlags.setMinimumSize(new java.awt.Dimension(320, 19));
        jTextFieldFlags.setPreferredSize(new java.awt.Dimension(320, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 4);
        jPanelGenerators.add(jTextFieldFlags, gridBagConstraints);

        jTextFieldFlagBits.setText("VkImageAspectFlagBits");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 4);
        jPanelGenerators.add(jTextFieldFlagBits, gridBagConstraints);

        jTextFieldHandles.setText("VkImage");
        jTextFieldHandles.setMinimumSize(new java.awt.Dimension(320, 19));
        jTextFieldHandles.setPreferredSize(new java.awt.Dimension(320, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 4);
        jPanelGenerators.add(jTextFieldHandles, gridBagConstraints);

        jTextFieldStructures.setText("VkStencilOpState");
        jTextFieldStructures.setMinimumSize(new java.awt.Dimension(320, 19));
        jTextFieldStructures.setPreferredSize(new java.awt.Dimension(320, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 4);
        jPanelGenerators.add(jTextFieldStructures, gridBagConstraints);

        jTextFieldUnions.setText("VkClearColorValue");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 4);
        jPanelGenerators.add(jTextFieldUnions, gridBagConstraints);

        jTextFieldInfos.setText("VkImageCreateInfo");
        jTextFieldInfos.setMinimumSize(new java.awt.Dimension(320, 19));
        jTextFieldInfos.setPreferredSize(new java.awt.Dimension(320, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 4);
        jPanelGenerators.add(jTextFieldInfos, gridBagConstraints);

        jTextFieldArrays.setText("UInt32Array");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 4);
        jPanelGenerators.add(jTextFieldArrays, gridBagConstraints);

        jTextFieldCallbacks.setText("PFN_vkCreateDebugUtilsMessengerEXT");
        jTextFieldCallbacks.setMinimumSize(new java.awt.Dimension(320, 19));
        jTextFieldCallbacks.setPreferredSize(new java.awt.Dimension(320, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 4);
        jPanelGenerators.add(jTextFieldCallbacks, gridBagConstraints);

        jTextFieldFunctions.setText("vkCreateImage");
        jTextFieldFunctions.setMinimumSize(new java.awt.Dimension(320, 19));
        jTextFieldFunctions.setPreferredSize(new java.awt.Dimension(320, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 4);
        jPanelGenerators.add(jTextFieldFunctions, gridBagConstraints);

        jTextFieldExtensions.setText("vkDestroyDebugUtilsMessengerEXT");
        jTextFieldExtensions.setMinimumSize(new java.awt.Dimension(320, 19));
        jTextFieldExtensions.setPreferredSize(new java.awt.Dimension(320, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 4);
        jPanelGenerators.add(jTextFieldExtensions, gridBagConstraints);

        jTextFieldDefines.setText("VK_TRUE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 4);
        jPanelGenerators.add(jTextFieldDefines, gridBagConstraints);

        jTextFieldMisc.setText("ToString");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 4, 4);
        jPanelGenerators.add(jTextFieldMisc, gridBagConstraints);

        jPanelHorizontalSpacer.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanelHorizontalSpacerLayout = new javax.swing.GroupLayout(jPanelHorizontalSpacer);
        jPanelHorizontalSpacer.setLayout(jPanelHorizontalSpacerLayout);
        jPanelHorizontalSpacerLayout.setHorizontalGroup(
                jPanelHorizontalSpacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelHorizontalSpacerLayout.setVerticalGroup(
                jPanelHorizontalSpacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanelGenerators.add(jPanelHorizontalSpacer, gridBagConstraints);

        javax.swing.GroupLayout jPanelVerticalLayout = new javax.swing.GroupLayout(jPanelVertical);
        jPanelVertical.setLayout(jPanelVerticalLayout);
        jPanelVerticalLayout.setHorizontalGroup(
                jPanelVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelVerticalLayout.setVerticalGroup(
                jPanelVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanelGenerators.add(jPanelVertical, gridBagConstraints);

        jScrollPaneGenerators.setViewportView(jPanelGenerators);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        getContentPane().add(jScrollPaneGenerators, gridBagConstraints);

        jPanelFooter.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWeights = new double[] {0.0, 0.0, 1.0, 0.0, 0.0};
        jPanel3Layout.rowWeights = new double[] {1.0};
        jPanelFooter.setLayout(jPanel3Layout);

        jButtonSelectAll.setText("Select all");
        jButtonSelectAll.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectAllActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanelFooter.add(jButtonSelectAll, gridBagConstraints);

        jButtonUnselectAll.setText("Unselect all");
        jButtonUnselectAll.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnselectAllActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanelFooter.add(jButtonUnselectAll, gridBagConstraints);

        jPanelDummy.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelDummy.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanelDummyLayout = new javax.swing.GroupLayout(jPanelDummy);
        jPanelDummy.setLayout(jPanelDummyLayout);
        jPanelDummyLayout.setHorizontalGroup(
                jPanelDummyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 465, Short.MAX_VALUE)
        );
        jPanelDummyLayout.setVerticalGroup(
                jPanelDummyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 33, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanelFooter.add(jPanelDummy, gridBagConstraints);

        jLabelStatus.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanelFooter.add(jLabelStatus, gridBagConstraints);

        jButtonGenerateSelected.setText("Generate selected");
        jButtonGenerateSelected.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateSelectedActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanelFooter.add(jButtonGenerateSelected, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 4, 4);
        getContentPane().add(jPanelFooter, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVulkanCoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVulkanCoreActionPerformed
        state.chooseVulkanCorePath();
    }

    private void jButtonOutputDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOutputDirectoryActionPerformed
        state.chooseOutputDirectoryPath();
    }

    private void jButtonTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTypesActionPerformed
        state.test(jTextFieldTypes.getText());
    }

    private void jButtonEnumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnumsActionPerformed
        state.test(jTextFieldEnums.getText());
    }

    private void jButtonFlagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlagsActionPerformed
        state.test(jTextFieldFlags.getText());
    }

    private void jButtonHandlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHandlesActionPerformed
        state.test(jTextFieldHandles.getText());
    }

    private void jButtonStructuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStructuresActionPerformed
        state.test(jTextFieldStructures.getText());
    }

    private void jButtonInfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateInfosActionPerformed
        state.test(jTextFieldInfos.getText());
    }

    private void jButtonCallbacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCallbacksActionPerformed
        state.test(jTextFieldCallbacks.getText());
    }

    private void jButtonFunctionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInterfaceActionPerformed
        state.test(jTextFieldFunctions.getText());
    }

    private void jButtonExtensionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtensionsActionPerformed
        state.test(jTextFieldExtensions.getText());
    }

    private void jButtonSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectAllActionPerformed
        state.selectAll();
    }

    private void jButtonUnselectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnselectAllActionPerformed
        state.unselectAll();
    }

    private void jButtonGenerateSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateSelectedActionPerformed
        state.generateSelected();
    }

    private void jButtonFlagBitsActionPerformed(java.awt.event.ActionEvent evt) {
        state.test(jTextFieldFlagBits.getText());
    }

    private void jButtonDefinesActionPerformed(java.awt.event.ActionEvent evt) {
        state.test(jTextFieldDefines.getText());
    }

    private void jButtonMiscActionPerformed(java.awt.event.ActionEvent evt) {
        state.test(jTextFieldMisc.getText());
    }

    private void jButtonSystemTypesActionPerformed(java.awt.event.ActionEvent evt) {
        state.test(jTextFieldSystemTypes.getText());
    }

    private void jButtonUnionsActionPerformed(java.awt.event.ActionEvent evt) {
        state.test(jTextFieldUnions.getText());
    }

    private void jButtonArraysActionPerformed(java.awt.event.ActionEvent evt) {
        state.test(jTextFieldArrays.getText());
    }

    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonArrays;
    public javax.swing.JButton jButtonCallbacks;
    public javax.swing.JButton jButtonDefines;
    public javax.swing.JButton jButtonEnums;
    public javax.swing.JButton jButtonExtensions;
    public javax.swing.JButton jButtonFlagBits;
    public javax.swing.JButton jButtonFlags;
    public javax.swing.JButton jButtonFunctions;
    public javax.swing.JButton jButtonGenerateSelected;
    public javax.swing.JButton jButtonHandles;
    public javax.swing.JButton jButtonInfos;
    public javax.swing.JButton jButtonMisc;
    public javax.swing.JButton jButtonOutputDirectory;
    public javax.swing.JButton jButtonSelectAll;
    public javax.swing.JButton jButtonStructures;
    public javax.swing.JButton jButtonSystemTypes;
    public javax.swing.JButton jButtonTypes;
    public javax.swing.JButton jButtonUnions;
    public javax.swing.JButton jButtonUnselectAll;
    public javax.swing.JButton jButtonVulkanCore;
    public javax.swing.JCheckBox jCheckBoxArrays;
    public javax.swing.JCheckBox jCheckBoxCallbacks;
    public javax.swing.JCheckBox jCheckBoxDefines;
    public javax.swing.JCheckBox jCheckBoxEnums;
    public javax.swing.JCheckBox jCheckBoxExtensions;
    public javax.swing.JCheckBox jCheckBoxFlagBits;
    public javax.swing.JCheckBox jCheckBoxFlags;
    public javax.swing.JCheckBox jCheckBoxFunctions;
    public javax.swing.JCheckBox jCheckBoxHandles;
    public javax.swing.JCheckBox jCheckBoxInfos;
    public javax.swing.JCheckBox jCheckBoxMisc;
    public javax.swing.JCheckBox jCheckBoxStructures;
    public javax.swing.JCheckBox jCheckBoxSystemTypes;
    public javax.swing.JCheckBox jCheckBoxTypes;
    public javax.swing.JCheckBox jCheckBoxUnions;
    public javax.swing.JLabel jLabelOutputDirectory;
    public javax.swing.JLabel jLabelStatus;
    public javax.swing.JLabel jLabelVulkanCore;
    public javax.swing.JPanel jPanelDummy;
    public javax.swing.JPanel jPanelFooter;
    public javax.swing.JPanel jPanelGenerators;
    public javax.swing.JPanel jPanelHorizontalSpacer;
    public javax.swing.JPanel jPanelPaths;
    public javax.swing.JPanel jPanelVertical;
    public javax.swing.JScrollPane jScrollPaneGenerators;
    public javax.swing.JTextField jTextFieldArrays;
    public javax.swing.JTextField jTextFieldCallbacks;
    public javax.swing.JTextField jTextFieldDefines;
    public javax.swing.JTextField jTextFieldEnums;
    public javax.swing.JTextField jTextFieldExtensions;
    public javax.swing.JTextField jTextFieldFlagBits;
    public javax.swing.JTextField jTextFieldFlags;
    public javax.swing.JTextField jTextFieldFunctions;
    public javax.swing.JTextField jTextFieldHandles;
    public javax.swing.JTextField jTextFieldInfos;
    public javax.swing.JTextField jTextFieldMisc;
    public javax.swing.JTextField jTextFieldOutputDirectory;
    public javax.swing.JTextField jTextFieldStructures;
    public javax.swing.JTextField jTextFieldSystemTypes;
    public javax.swing.JTextField jTextFieldTypes;
    public javax.swing.JTextField jTextFieldUnions;
    public javax.swing.JTextField jTextFieldVulkanCorePath;
    // End of variables declaration//GEN-END:variables
}
